### ISSUE TITLE
Problem in build.gradle

### ISSUE THREAD

**Issue by shivangsri** [tambapps/P2P-File-Sharing#5]
When running code on android studio the line below has some error

def admobProperties = new Properties()
admobProperties.load(new FileInputStream(rootProject.file("admob.properties")))

**Comment by tambapps** [comment]
Hello, sorry for the delay. It should now be fixed. You can now build the app even if the `admob.properties` file doesn't exists

**Comment by shivangsri** [comment]
Still showing error that google-services.json is missing.
Here is the error

Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\shiva\Downloads\P2P-File-Sharing-master\android_app\app\src\debug\google-services.json
  C:\Users\shiva\Downloads\P2P-File-Sharing-master\android_app\app\src\google-services.json
  C:\Users\shiva\Downloads\P2P-File-Sharing-master\android_app\app\google-services.json

**Comment by shivangsri** [comment]
Can you please provide apk of this app?

**Comment by tambapps** [comment]
Oh, indeed there's also this file. Well, you can also remove firebase dependencies and firebase-related code (I only use it for analytics and crashlytics so removing it shouldn't break the app)

**Comment by tambapps** [comment]
Why do you want an APK? Can't you download the app from the Google playstore?
